<tr>
    <td><a href="<?=
        $this->url(
            'application/default',
            array(
                'controller' => 'participante',
                'action' => 'edit',
                'key' => $this->codigo_partic
            )
        )
    ?>"><?=$this->codigo_partic?></a></td>
    <td><?=$this->nome?></td>
    <td><?=$this->regiao?></td>
    <td><a href="<?=
        $this->url(
            'application/default',
            array(
                'controller' => 'participante',
                'action' => 'delete',
                'key' => $this->codigo_partic
            )
        )
    ?>">Excluir</a></td>
</tr>