<h1>Cadastro de Participantes</h1>
<a href="<?=$this
->url(
    'application/default',
    array(
        'controller' => 'participante',
        'action' => 'edit'
    )
)?>">Incluir</a>

<table>
    <thead>
        <tr>
            <th>Codigo</th>
            <th>Nome</th>
            <th>Codigo Regiao</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partialLoop('models_participante.phtml', $this->models)?>
    </tbody>
</table>